In [64]:
#load all required libreaies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import os
import sys
import warnings
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from scipy.io import arff

In [65]:
#load the data called Autism_data.arff
data = pd.read_csv('Autism_Data.arff')
data.head()

A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0         1         1         1         1         0         0         1   
1         1         1         0         1         0         0         0   
2         1         1         0         1         1         0         1   
3         1         1         0         1         0         0         1   
4         1         0         0         0         0         0         0   

   A8_Score  A9_Score  A10_Score  ... gender       ethnicity jundice austim  \
0         1         0          0  ...      f  White-European      no     no   
1         1         0          1  ...      m          Latino      no    yes   
2         1         1          1  ...      m          Latino     yes    yes   
3         1         0          1  ...      f  White-European      no    yes   
4         1         0          0  ...      f               ?      no     no   

     contry_of_res used_app_before result       age_desc relation Class/ASD  
0  'United States'              no      6  '18 and more'     Self        NO  
1           Brazil              no      5  '18 and more'     Self        NO  
2            Spain              no      8  '18 and more'   Parent       YES  
3  'United States'              no      6  '18 and more'     Self        NO  
4            Egypt              no      2  '18 and more'        ?        NO  

[5 rows x 21 columns]

In [66]:
#count NA values in each of the columns
for i in data.columns:
    print(i, data[i].isna().sum())

A1_Score 0
A2_Score 0
A3_Score 0
A4_Score 0
A5_Score 0
A6_Score 0
A7_Score 0
A8_Score 0
A9_Score 0
A10_Score 0
age 0
gender 0
ethnicity 0
jundice 0
austim 0
contry_of_res 0
used_app_before 0
result 0
age_desc 0
relation 0
Class/ASD 0


In [67]:
#print unique values in each of the columns
for i in data.columns:
    print(i, data[i].unique())

A1_Score [1 0]
A2_Score [1 0]
A3_Score [1 0]
A4_Score [1 0]
A5_Score [0 1]
A6_Score [0 1]
A7_Score [1 0]
A8_Score [1 0]
A9_Score [0 1]
A10_Score [0 1]
age ['26' '24' '27' '35' '40' '36' '17' '64' '29' '33' '18' '31' '30' '34'
 '38' '42' '43' '48' '37' '55' '50' '53' '20' '28' '21' '383' '47' '32'
 '44' '?' '19' '58' '45' '22' '39' '25' '23' '54' '60' '41' '46' '56' '61'
 '59' '52' '49' '51']
gender ['f' 'm']
ethnicity ['White-European' 'Latino' '?' 'Others' 'Black' 'Asian'
 "'Middle Eastern '" 'Pasifika' "'South Asian'" 'Hispanic' 'Turkish'
 'others']
jundice ['no' 'yes']
austim ['no' 'yes']
contry_of_res ["'United States'" 'Brazil' 'Spain' 'Egypt' "'New Zealand'" 'Bahamas'
 'Burundi' 'Austria' 'Argentina' 'Jordan' 'Ireland'
 "'United Arab Emirates'" 'Afghanistan' 'Lebanon' "'United Kingdom'"
 "'South Africa'" 'Italy' 'Pakistan' 'Bangladesh' 'Chile' 'France' 'China'
 'Australia' 'Canada' "'Saudi Arabia'" 'Netherlands' 'Romania' 'Sweden'
 'Tonga' 'Oman' 'India' 'Philippines' "'Sri Lanka

Two columns contains values of ? in their columns. This has to do something, why is there. Filter only these columns and see if there is 
association.

In [68]:
#look at two columns: ethnicity and relation
data[["ethnicity", "relation"]]

#check if ethinicity is ?, is the relation also ?
for i in data.columns:
    if (data[i]=="?").any():
        print(i)

age
ethnicity
relation


In [69]:
#for all columns with ?, replace wtih NaN
for i in data.columns:
    if (data[i]=="?").any():
        data[i] = data[i].replace("?", np.nan)

The data is cleaned. Lets formulate the questions and hypothesis that what can be answered
Maybe it is important to see like which of the 10 variables has the most important. But, before important and quick tips ??
Don't forget encoding. Machine does not character as you do. Standarization not requierd, because most columns are binary and categorical, 
and all are one hot encoded.

In [70]:
#perform one hot ecnodig for all the columns with object data type
data_encoded = pd.get_dummies(data, columns=["gender", "ethnicity", "jundice", 
                                     "austim", "contry_of_res", "used_app_before", "relation", "Class/ASD"])

data_encoded


A1_Score  A2_Score  A3_Score  A4_Score  A5_Score  A6_Score  A7_Score  \
0           1         1         1         1         0         0         1   
1           1         1         0         1         0         0         0   
2           1         1         0         1         1         0         1   
3           1         1         0         1         0         0         1   
4           1         0         0         0         0         0         0   
..        ...       ...       ...       ...       ...       ...       ...   
699         0         1         0         1         1         0         1   
700         1         0         0         0         0         0         0   
701         1         0         1         1         1         0         1   
702         1         0         0         1         1         0         1   
703         1         0         1         1         1         0         1   

     A8_Score  A9_Score  A10_Score  ... contry_of_res_Uruguay  \
0           1         0          0  ...                 False   
1           1         0          1  ...                 False   
2           1         1          1  ...                 False   
3           1         0          1  ...                 False   
4           1         0          0  ...                 False   
..        ...       ...        ...  ...                   ...   
699         1         1          1  ...                 False   
700         1         0          1  ...                 False   
701         1         0          1  ...                 False   
702         0         1          1  ...                 False   
703         1         1          1  ...                 False   

     used_app_before_no used_app_before_yes  \
0                  True               False   
1                  True               False   
2                  True               False   
3                  True               False   
4                  True               False   
..                  ...                 ...   
699                True               False   
700                True               False   
701                True               False   
702                True               False   
703                True               False   

     relation_'Health care professional'  relation_Others  relation_Parent  \
0                                  False            False            False   
1                                  False            False            False   
2                                  False            False             True   
3                                  False            False            False   
4                                  False            False            False   
..                                   ...              ...              ...   
699                                False            False            False   
700                                False            False             True   
701                                False            False            False   
702                                False            False            False   
703                                False            False            False   

     relation_Relative  relation_Self  Class/ASD_NO  Class/ASD_YES  
0                False           True          True          False  
1                False           True          True          False  
2                False          False         False           True  
3                False           True          True          False  
4                False          False          True          False  
..                 ...            ...           ...            ...  
699              False           True         False           True  
700              False          False          True          False  
701              False          False         False           True  
702              False           True          True          False  
703              False           True 

In [71]:
#run another hot enoding methods from one hot encoding
from sklearn.preprocessing import OneHotEncoder

#creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
data_encoded_onehot = pd.DataFrame(enc.fit_transform(data[["gender", "ethnicity", "jundice", 
                                     "austim", "contry_of_res", "used_app_before", "relation", "Class/ASD"]]).toarray())

data_encoded_onehot

0    1    2    3    4    5    6    7    8    9   ...   85   86   87  \
0    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
1    0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  1.0  0.0  0.0   
3    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
4    1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
699  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
700  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
701  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
702  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   
703  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.0  0.0  0.0   

      88   89   90   91   92   93   94  
0    0.0  0.0  0.0  1.0  0.0  1.0  0.0  
1    0.0  0.0  0.0  1.0  0.0  1.0  0.0  
2    0.0  1.0  0.0  0.0  0.0  0.0  1.0  
3    0.0  0.0  0.0  1.0  0.0  1.0  0.0  
4    0.0  0.0  0.0  0.0  1.0  1.0  0.0  
..   ...  ...  ...  ...  ...  ...  ...  
699  0.0  0.0  0.0  1.0  0.0  0.0  1.0  
700  0.0  1.0  0.0  0.0  0.0  1.0  0.0  
701  0.0  0.0  0.0  0.0  1.0  0.0  1.0  
702  0.0  0.0  0.0  1.0  0.0  1.0  0.0  
703  0.0  0.0  0.0  1.0  0.0  0.0  1.0  

[704 rows x 95 columns]

In [76]:
# select from first column to second last column
X = data_encoded_onehot.iloc[:, :-1]

# select the last column
y = data_encoded_onehot.iloc[:, -1]

#split the data into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [77]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((563, 94), (141, 94), (563,), (141,))

This is a classfication job. So, all machine learning models capabale of classification can be used here. Linear regression is no chance, otherwise I would simply use it but it does not have the ability to classify. The couple avialable options from me are 
1. Logistic Regression
2. Decision Tree
3. Random Forest

I will test will all these models, runs for couple epochs and evaluate the best model with highest accuracy.

In [89]:
# Logistic regression model
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)

#predict the model
y_pred = logistic_model.predict(X_test)

In [103]:
#calculate the accuracy of the model
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)

#calculate the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix_log = confusion_matrix(y_test, y_pred) 

confusion_matrix_log, accuracy


(array([[105,   0],
        [  0,  36]], dtype=int64),
 1.0)

In [106]:
#Decision Tree model
from sklearn.tree import DecisionTreeClassifier
decision_tree_model = DecisionTreeClassifier()
decision_tree_model.fit(X_train, y_train)

#predict the model
y_pred = decision_tree_model.predict(X_test)

# #calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

# confusion_matrix, accuracy
confusion_matrix_dec = confusion_matrix(y_test, y_pred)

confusion_matrix_dec, accuracy

(array([[105,   0],
        [  0,  36]], dtype=int64),
 1.0)

In [107]:
#Random Forest model
from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier()
random_forest_model.fit(X_train, y_train)

#tune the model
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth': [10, 20, 30, 40, 50]
}

grid_search = GridSearchCV(estimator=random_forest_model, param_grid=param_grid, cv=5)

grid_search.fit(X_train, y_train)

c:\Users\sujan\anaconda3\envs\sujan_env\lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
75 fits failed out of a total of 225.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
75 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\sujan\anaconda3\envs\sujan_env\lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\sujan\anaconda3\envs\sujan_env\lib\site-packages\sklearn\base.py", line 1145, in wrapper
    estimator._validate_params()
  File "c:\Users\sujan\anaconda3\envs\sujan_env\lib\site-packages\sklearn\base.py", line 638, in _validate_params
    validate_parameter_con

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [10, 20, 30, 40, 50],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [100, 200, 300]})

In [109]:
#predict the model
y_pred = grid_search.predict(X_test)

#calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

#create confusion matrix
confusion_matrix_random_forest = confusion_matrix(y_test, y_pred)

# confusion_matrix, accuracy
confusion_matrix_random_forest, accuracy

(array([[105,   0],
        [  0,  36]], dtype=int64),
 1.0)

For all models, the accuracy is 100%. But is it not good ? 
-seems like the machine model learnt too well. Unless sombody gives a random data, I still can' t say. It should almost be imposisble for these
machine to learn it so well that they have 100%.

Let's reduce the